apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DATABASE_NAME: ZGphbmdv
  DATABASE_USER: cHNxbF9hZG1pbg==
  DATABASE_PASSWORD: Y0hOeGJIWnBjMmh1ZFFv
  DATABASE_SERVICE_HOST: dmlzaG51LXBzcWwuY3g4eGhkNG5sMzBoLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  DATABASE_SERVICE_PORT: NTQzMg==
