apiVersion: v1
kind: Service
metadata:
  name: django-app-svc
  labels:
    app: django-app  
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    name: django-app
  type: LoadBalancer
